<!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="styleWelcome.css"> <!-- connection css -->
        <link href="https://fonts.googleapis.com/css2?family=Roboto+Mono&display=swap" rel="stylesheet">
        <title>Welcome to our community</title>
    </head>
    <body>
<a href="index.html" class="form_title">
<svg width="67" height="78" viewBox="0 0 67 78" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M5.39999 55.3333V4L34.2 29.6667M5.39999 55.3333L22.68 74M5.39999 55.3333L19.8 42.5M34.2 29.6667L63 4M34.2 29.6667L54.36 50.6667L63 60.3043M34.2 29.6667L19.8 42.5M19.8 42.5L28.44 50.6667" stroke="#5353AF" stroke-width="8" stroke-linecap="round" stroke-linejoin="round"/>
<path d="M3 55.3333V4L31.8 29.6667M3 55.3333L20.28 74M3 55.3333L17.4 42.5M31.8 29.6667L60.6 4M31.8 29.6667L51.96 50.6667L60.6 59.7971M31.8 29.6667L17.4 42.5M17.4 42.5L26.04 50.6667" stroke="white" stroke-width="5" stroke-linecap="round" stroke-linejoin="round"/>
      </svg>
    </a>
  <h1>👋<?= $name ?></h1> <!-- Name output -->
</body>
</html>