<!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="styleWelcom.css"> <!-- connection css -->
        <title>Welcom</title>
    </head>
    <body>
        <h1>Welcom to the site, <?= $name ?></h1> <!-- Name output -->
        <p>Тут надо написать какое-то приветствие.</p>
        <a href='../index.html'>Read News</a> <!-- Go to main page -->
    </body>
    </html>